// export const GET_MOVIES_FROM_STATE = "GET_MOVIES_FROM_STATE";
// export const SET_MOVIES_IN_STATE = "SET_MOVIES_IN_STATE";

export const GET_SEARCH_VALUES = "GET_SEARCH_VALUES";
export const SET_SEARCH_VALUES = "SET_SEARCH_VALUES";
export const FETCH_MOVIES = "FETCH_MOVIES"